# Generated by Django 2.1.3 on 2018-11-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_auto_20181117_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image/promotion')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.Good'),
        ),
    ]
