# Generated by Django 2.1.3 on 2018-11-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0005_goodcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
