# Generated by Django 2.1.3 on 2018-11-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0006_good_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='sales',
            field=models.IntegerField(null=True),
        ),
    ]
