# Generated by Django 2.1.3 on 2018-12-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0009_auto_20181120_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='sales',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
